export const USER_LOGIN_STARTED = 'USER_LOGIN_STARTED';
export const USER_LOGIN_FINISHED = 'USER_LOGIN_FINISHED';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const USER_LOGOUT_STARTED = 'USER_LOGOUT_STARTED';
export const USER_LOGOUT_FINISHED = 'USER_LOGOUT_FINISHED';
export const USER_LOGOUT_ERROR = 'USER_LOGOUT_ERROR';

